kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    when:
      branch:
        - main
    commands:
      - cd /mnt/launcher
      - git pull
      - yarn
      - yarn build
