/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registration from './registration'
export type { registration }
export type { AmbrusStudioSaler } from './AmbrusStudioSaler'
export type { E4CAlpha } from './E4CAlpha'
export type { E4CBadge } from './E4CBadge'
export type { E4CRanger } from './E4CRanger'
export type { E4CRangerHolder } from './E4CRangerHolder'
export type { IMintable } from './IMintable'
export type { Mintable } from './Mintable'
export type { TestERC721 } from './TestERC721'
