/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { IMintableERC721, IMintableERC721Interface } from '../../contracts/IMintableERC721'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'to',
        type: 'address',
      },
    ],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

export class IMintableERC721__factory {
  static readonly abi = _abi
  static createInterface(): IMintableERC721Interface {
    return new utils.Interface(_abi) as IMintableERC721Interface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMintableERC721 {
    return new Contract(address, _abi, signerOrProvider) as IMintableERC721
  }
}
