/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMX__factory } from './IMX__factory'
export { Registration__factory } from './Registration__factory'
